language: ruby
rvm:
  - 2.4
services:
  - couchdb
before_install:
  - gem update bundler
before_script:
  - sudo cp config.yml.sample config.yml
  - curl -X PUT localhost:5984/orcid_taxonomist
  - sudo ./bin/app.rb -i
branches:
  only:
      - master